name: task_management_application
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.3.4
  email_validator: ^2.1.17
  flutter_hooks: ^0.20.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.0
  http: ^1.1.0
  json_serializable: ^6.7.1
  logging: ^1.2.0
  retrofit: ^4.0.3
  url_strategy: ^0.2.0
  uuid: ^4.2.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  drift: ^2.13.1
  local_auth: ^2.1.7
  amazon_cognito_identity_dart_2: ^3.6.0
  kanban_board: ^0.1.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  device_preview: ^1.1.0
  flutter_lints: ^2.0.3
  retrofit_generator: ^8.0.3
  source_gen: ^1.4.0
  mockito: ^5.4.2


flutter:
  uses-material-design: true
  generate: true